name: dungeon_creator
description: A simple dungeon map creator.
version: 0.0.1
#homepage: https://www.example.com
#author: terrasea <email@example.com>

environment:
  sdk: '>=2.0.0-dev.23.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.32+1
  mockito: ^3.0.0-alpha

transformers:
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc